air:
  app_name: goproxy-china
  debug_mode: true
  address: 'localhost:8080'
  minifier_enabled: true
  gzip_enabled: true
  coffer_enabled: true
  i18n_enabled: true
zerolog:
  level: debug
goproxy:
  go_bin_name: go
  go_bin_fetch_timeout: 60s
  proxied_sumdbs:
    - sum.golang.org
  local_cache_root: /tmp
  auto_redirect: false
  auto_redirect_min_size: 10485760
  replace:
    gitlab.company.com: 'user:pass@gitlab.company.com'
  basic:
    enable: false
    auth:
      - "" # user:pass base64 encode
cache:
  disk:
    root: ".cache"